# Generated by Django 6.0.6 on 2026-07-24 11:31

from django.db import migrations, models

ROLE_RENAMES = {
    "PROPRIETAIRE": "VENDEUR",
    "INVESTISSEUR": "ACHETEUR",
}


def rename_roles_forward(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for old, new in ROLE_RENAMES.items():
        User.objects.filter(role=old).update(role=new)


def rename_roles_backward(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for old, new in ROLE_RENAMES.items():
        User.objects.filter(role=new).update(role=old)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("VENDEUR", "Vendeur"),
                    ("ACHETEUR", "Acheteur"),
                    ("ADMIN", "Administrateur"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(rename_roles_forward, rename_roles_backward),
    ]
