# Generated by Django 6.0.6 on 2026-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VENDEUR", "Vendeur"),
                    ("ACHETEUR", "Acheteur"),
                    ("ADMIN", "Administrateur"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
