# Generated by Django 6.0.8 on 2026-09-29 11:07

from django.db import migrations, models


def marquer_comptes_sms_verifies(apps, schema_editor):
    # Les comptes créés par connexion SMS (email synthétique @tel.akal.local)
    # ont prouvé leur numéro : ils restent joignables par la connexion SMS.
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email__endswith='@tel.akal.local').exclude(
        telephone__isnull=True,
    ).exclude(telephone='').update(telephone_verifie=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telephone_verifie",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(marquer_comptes_sms_verifies, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telephone_verifie", True)),
                fields=("telephone",),
                name="user_telephone_verifie_unique",
            ),
        ),
    ]
