"""
Django settings for akal project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
# pyrefly: ignore [missing-import]
import environ

env = environ.Env()

# GDAL / GEOS — Chemins spécifiques pour le développement sous Windows.
# Sur Linux/Docker, les paquets apt (gdal-bin, libgdal-dev) sont détectés automatiquement.
if os.name == 'nt':
    GDAL_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\18\bin\libgdal-35.dll'
    GEOS_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\18\bin\libgeos_c.dll'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# .parent x3 car base.py est dans akal/settings/, donc : settings -> akal -> akal_project
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Lecture du fichier .env
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# DEBUG et ALLOWED_HOSTS sont définis dans dev.py et prod.py


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    # Apps tierces
    'rest_framework',
    'rest_framework_gis',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',
    'django_filters',
    # django-axes (audit final du 20/08, correction du P1 sécurité admin) —
    # cf. AUTHENTICATION_BACKENDS et bloc AXES_* plus bas pour la config.
    'axes',

    # Apps du projet
    'accounts',
    'geo',
    'annonces',
    'messaging',
    # Pipeline AgriScore (collecte multi-source → score parcelle). Le cœur
    # est du Python pur (agriscore/{scoring,aggregation,interpretation,
    # agents,orchestrateur}.py) ; l'app n'ajoute que le flag de config
    # (ConfigurationAgriScore) et l'endpoint /api/parcelles/<id>/passeport/.
    'agriscore',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # django-axes — DOIT être le dernier middleware (recommandation du
    # package) : il traduit un verrouillage détecté plus haut dans la pile
    # (AUTHENTICATION_BACKENDS, cf. bloc AXES_* plus bas) en réponse HTTP 403
    # lisible, une fois que la vue a déjà tenté de répondre.
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'akal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'akal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}
DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'

# Custom User model
AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ──────────────────────────────────────────────
# STOCKAGE MÉDIA — MinIO (dev) / S3-compatible (prod) via django-storages
# ──────────────────────────────────────────────
# Contrat §4.7 : bucket public en lecture, URLs absolues stables, jamais le
# domaine de l'API Django. Mêmes settings dev/prod — seule la valeur des
# variables d'env change (endpoint MinIO local vs S3/CDN prod).
#
# MEDIA_URL n'est plus défini : avec STORAGES['default'] sur S3Storage,
# FieldFile.url délègue au storage (qui construit l'URL depuis les AWS_S3_*
# ci-dessous) — MEDIA_URL serait une deuxième source de vérité pouvant
# diverger silencieusement (ex. si AWS_S3_CUSTOM_DOMAIN change un jour).

AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='akal-media')
AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL', default='http://localhost:9000')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_ADDRESSING_STYLE = 'path'    # requis par MinIO (pas de sous-domaine par bucket)
AWS_QUERYSTRING_AUTH = False        # bucket public en lecture, pas d'URL présignée (§4.7)
AWS_DEFAULT_ACL = None              # la policy du bucket gère la lecture publique
AWS_S3_FILE_OVERWRITE = False       # chaque objet est immuable une fois uploadé
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=31536000',  # photos immuables : cache navigateur 1 an
}

# Domaine public devant le bucket en prod (CDN, ex. media.akal.ma) — vide en
# dev, on sert alors directement depuis l'endpoint MinIO local.
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default='')
# Protocole des URLs publiques construites depuis AWS_S3_CUSTOM_DOMAIN.
# 'https:' en prod (CDN) ; surchargeable en 'http:' pour un MinIO local servi
# en clair (ex. docker-compose full-stack, où CUSTOM_DOMAIN vaut
# `localhost:9000/akal-media` — endpoint + bucket, MinIO étant en path-style).
AWS_S3_URL_PROTOCOL = env('AWS_S3_URL_PROTOCOL', default='https:')

# Vérification TLS de l'endpoint S3 — sans effet ici (endpoint MinIO dev en
# http:// simple) ; pertinent seulement si un endpoint auto-signé passe un
# jour en https:// en local.
AWS_S3_VERIFY = env.bool('AWS_S3_VERIFY', default=True)

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',  # whitenoise inchangé
    },
}

# Cache local de téléchargement pour les scripts de seed (Unsplash) — plus
# jamais servi directement (les médias réels vivent sur MinIO/S3 ci-dessus) ;
# gardé uniquement parce que seed_parcelles.py s'en sert comme répertoire de
# travail local avant upload.
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ──────────────────────────────────────────────
# DJANGO REST FRAMEWORK
# ──────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    # Contrat §4.4 : prix_mad/surface_ha sont des nombres JSON, pas des
    # chaînes. DRF sérialise les DecimalField en string par défaut.
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CookieJWTAuthentication',
    ],
    # ──────────────────────────────────────────────
    # Rate-limiting (audit go-live du 2026-08-10) — deux niveaux :
    #   1. Un plancher global (anon/user) sur TOUS les endpoints, y compris
    #      ceux qui n'ont jamais été explicitement pensés pour ça (référentiel
    #      geo, catalogue, favoris...) — filet de sécurité, pas une limite
    #      métier fine. anon est volontairement plus permissif qu'un vrai
    #      anti-scraping : bloquer un abus grossier (script en boucle serrée),
    #      pas gêner un parcours de navigation normal (pagination, filtres).
    #   2. Des scopes métier serrés sur les actions d'écriture les plus
    #      sensibles (signup, dépôt d'annonce, upload photo, envoi de
    #      message) — cf. chaque vue pour le throttle_scope appliqué.
    # Valeurs de départ, à ajuster avec de la vraie donnée de trafic une fois
    # en prod — pas des constantes gravées dans le marbre.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # anon/user volontairement larges : ce sont des planchers globaux
        # (filet anti-script-en-boucle), pas des limites métier précises —
        # celles-ci vivent dans les scopes ci-dessous. Des valeurs trop
        # serrées ici feraient plus de dégâts que de bien : elles finiraient
        # par déclencher sur un simple parcours de navigation normal (ou,
        # en test, sur le volume cumulé de la suite — le test client Django
        # partage la même IP 127.0.0.1 pour toute la suite, donc un seuil
        # anon trop bas romprait des tests sans rapport avec le throttling).
        'anon': '1000/hour',
        'user': '5000/hour',
        'login': '5/min',
        'password_reset': '3/hour',
        'signup': '5/hour',
        # Connexion Google (GoogleLoginView) — chaque appel = une vérification
        # de jeton côté Google + potentiellement une création de compte.
        'google': '20/hour',
        'annonce_create': '20/hour',
        'photo_upload': '30/hour',
        'message': '40/hour',
        # Lien WhatsApp (WhatsAppLienAPIView, hardening 2026-08-30) — chaque
        # appel révèle un numéro de vendeur (dans l'URL wa.me). Authentifié
        # déjà, mais scope dédié pour qu'un compte ne puisse pas énumérer
        # tous les numéros du catalogue en boucle.
        'whatsapp': '60/hour',
        # Comptage de vues de fiche (EnregistrerVueAPIView, 2026-08-31) —
        # beacon anonyme envoyé par le front au montage de /parcelles/<slug>.
        # Large : un visiteur peut légitimement rouvrir plusieurs fiches à la
        # suite ; la déduplication (24 h par annonce/IP/jour, côté vue) borne
        # déjà l'impact réel sur le compteur, ce scope ne fait que couper un
        # script qui martèlerait l'endpoint.
        'vue': '120/hour',
        # Passeport AgriScore (PasseportParcelleAPIView) — un appel non caché
        # déclenche jusqu'à 5 requêtes vers des API externes (Copernicus,
        # Open-Meteo, SoilGrids, OSRM). Défense en profondeur, cf. la docstring
        # de la vue : ici on plafonne le nombre de parcelles DISTINCTES qu'une
        # IP peut faire calculer à froid (15/h × 5 = 75 appels externes max,
        # et seulement pour des parcelles jamais vues) ; le cache du passeport
        # assemblé par parcelle (TTL 12 h) et le verrou de calcul font le
        # reste. 15/h reste large pour un usage réel (comparer une dizaine de
        # parcelles depuis les fiches).
        'passeport': '15/hour',
    },
}


# ──────────────────────────────────────────────
# AUTH — JWT via cookies httpOnly (avenant v1.1, cf. docs/plans)
# ──────────────────────────────────────────────

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_COOKIE_ACCESS': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    # '/' et non '/api/auth/' (audit du 16/08) : frontend/src/proxy.ts lit ce
    # cookie sur CHAQUE navigation de page (config.matcher y couvre tout le
    # site) pour rafraîchir la session en silence — avec Path='/api/auth/',
    # le navigateur ne l'attachait jamais à une requête vers /publier,
    # /favoris, etc., et le refresh échouait systématiquement (401 côté
    # /api/auth/refresh/, faute de cookie transmis), pas seulement lors d'une
    # requête ponctuelle. Reproduit et confirmé par inspection directe des
    # cookies du navigateur, pas supposé.
    'AUTH_COOKIE_REFRESH_PATH': '/',
    # Défauts sûrs pour la prod (frontend et backend sur des sites
    # différents, cf. prod.py) ; dev.py les assouplit pour localhost en HTTP.
    'AUTH_COOKIE_SECURE': True,
    'AUTH_COOKIE_SAMESITE': 'None',
}


# ──────────────────────────────────────────────
# DJANGO-AXES — anti-brute-force sur /admin/ (audit final du 20/08, P1)
# ──────────────────────────────────────────────
#
# L'audit a constaté que le throttling DRF ci-dessus (login/signup/...) ne
# couvre que les endpoints DRF de accounts/ — la vue de connexion Django
# Admin classique (/admin/login/) n'en a jamais bénéficié et peut être
# attaquée par force brute sans aucun ralentissement.
#
# AxesBackend s'insère AVANT ModelBackend dans la chaîne d'authentification
# Django (authenticate()) : il bloque une tentative déjà verrouillée avant
# même que ModelBackend ne vérifie le mot de passe. Il n'authentifie jamais
# lui-même — cf. axes/backends.py.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Portée strictement limitée à /admin/ (AXES_ONLY_ADMIN_SITE) : la connexion
# JWT de l'app (LoginView, accounts/views.py) passe elle aussi par
# authenticate() — donc par AxesBackend — mais dispose déjà de son propre
# throttle_scope 'login' (5/min, cf. REST_FRAMEWORK ci-dessus). Sans cette
# restriction, axes suivrait EN PLUS les tentatives sur la connexion grand
# public et pourrait la verrouiller (par défaut, un verrou axes est
# permanent tant qu'un staff ne le lève pas manuellement en admin — cf.
# AXES_COOLOFF_TIME plus bas) : une dégradation du mécanisme existant,
# jamais voulue ici. Vérifié dans axes/handlers/base.py::is_allowed() —
# AXES_ONLY_ADMIN_SITE=True exempte totalement les requêtes hors admin du
# suivi, pas seulement de la réponse de verrouillage.
AXES_ONLY_ADMIN_SITE = True

# 5 échecs avant verrouillage — légèrement plus permissif que le défaut du
# package (3) : un admin qui se trompe deux fois de mot de passe ne doit pas
# se verrouiller lui-même pour la journée.
AXES_FAILURE_LIMIT = 5

# Verrou temporaire (30 min), jamais permanent : contrairement au défaut du
# package (AXES_COOLOFF_TIME=None => verrou permanent, levé uniquement par
# un staff en base), un verrou qui s'auto-résout après une pause raisonnable
# ne rend jamais le panel injoignable pour un administrateur légitime en
# pleine démo/soutenance.
AXES_COOLOFF_TIME = timedelta(minutes=30)

# Verrouille sur CHACUN des deux critères indépendamment (liste à plat, pas
# imbriquée — sémantique "OR" du package) : une IP qui teste beaucoup de
# comptes différents est bloquée par IP, un compte attaqué depuis plusieurs
# IP (botnet) est bloqué par identifiant — les deux protections demandées
# par l'audit, pas une combinaison stricte des deux qui laisserait passer
# l'un ou l'autre cas isolément.
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# Une connexion réussie remet le compteur d'échecs à zéro — un admin qui se
# trompe puis réussit ne doit pas rester à un échec de la limite.
AXES_RESET_ON_SUCCESS = True

# Historique des tentatives visible dans /admin/ elle-même (modèles axes
# AccessAttempt/AccessLog) — logs exploitables sans dépendre d'un outil
# externe, cf. exigence de l'audit.
AXES_ENABLE_ADMIN = True

# Messages explicitement en français (le package les fournit par défaut en
# anglais) — même convention que SignupSerializer/UniqueValidator
# (accounts/serializers.py) : ce projet n'a jamais compté sur la traduction
# automatique d'un message tiers pour un texte visible par un humain.
AXES_COOLOFF_MESSAGE = 'Compte verrouillé : trop de tentatives de connexion. Réessayez dans quelques minutes.'
AXES_PERMALOCK_MESSAGE = 'Compte verrouillé : trop de tentatives de connexion. Contactez un administrateur pour le déverrouiller.'


# ──────────────────────────────────────────────
# DRF-SPECTACULAR — OpenAPI / Swagger
# ──────────────────────────────────────────────

SPECTACULAR_SETTINGS = {
    'TITLE': 'AKAL API',
    'DESCRIPTION': 'API de la plateforme AKAL — vente de terrains agricoles au Maroc',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# ──────────────────────────────────────────────
# CORS — django-cors-headers
# ──────────────────────────────────────────────

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]

# Requis pour que les cookies JWT (httpOnly) passent sur les requêtes
# cross-origin du frontend (fetch avec credentials: "include").
CORS_ALLOW_CREDENTIALS = True

# Origine du frontend, pour construire les liens absolus envoyés par email
# (réinitialisation de mot de passe). Distinct de CORS_ALLOWED_ORIGINS
# ci-dessus (qui liste des origines API-side autorisées) : ici une seule
# valeur, celle vers laquelle rediriger un humain.
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')


# ──────────────────────────────────────────────
# GOOGLE OAUTH — connexion Google (GoogleLoginView, accounts/auth_api_views.py)
# ──────────────────────────────────────────────
#
# Client ID OAuth 2.0 (Google Cloud Console → APIs et services →
# Identifiants), distinct de Firebase : GoogleLoginView vérifie le jeton
# directement via google-auth (id_token.verify_oauth2_token), sans passer par
# firebase_admin (cf. section Firebase du README backend). Vide par défaut
# pour ne pas faire planter manage.py check/test/runserver tant que la
# variable n'est pas provisionnée — GoogleLoginView répond alors 503 plutôt
# que de vérifier les jetons contre un client ID codé en dur.
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')


# ──────────────────────────────────────────────
# AGRISCORE — pipeline d'enrichissement (agriscore/)
# ──────────────────────────────────────────────
#
# Identifiants des sources externes des agents. Vides par défaut, même logique
# que SENTRY_DSN / GOOGLE_CLIENT_ID : sans provisionnement, l'agent concerné
# renvoie statut="indisponible" (jamais d'exception, le pipeline continue avec
# les autres dimensions) — check/test/runserver passent sans clé.
#
#   - topo  : Open-Meteo Elevation (GLO-90) par défaut, AUCUNE clé.
#             OPENTOPOGRAPHY_API_KEY sert uniquement à l'agent optionnel
#             AgentTopoReel (GLO-30) si on le passe explicitement à
#             l'orchestrateur — inutile pour AGENTS_DEFAUT.
#   - ndvi  : Copernicus Data Space Ecosystem (Sentinel-2) — OAuth2 client
#   - climat: Open-Meteo archive — aucune clé
#   - sol   : SoilGrids (ISRIC) — aucune clé
#   - acces : OSRM / OpenStreetMap — aucune clé
OPENTOPOGRAPHY_API_KEY = env('OPENTOPOGRAPHY_API_KEY', default='')
CDSE_CLIENT_ID = env('CDSE_CLIENT_ID', default='')
CDSE_CLIENT_SECRET = env('CDSE_CLIENT_SECRET', default='')

# Timeout (s) des appels HTTP des agents réels du pipeline AgriScore.
AGRISCORE_HTTP_TIMEOUT_S = env.float('AGRISCORE_HTTP_TIMEOUT_S', default=10.0)


# ──────────────────────────────────────────────
# DATASET — simulated / scraped (2026-08-11)
# ──────────────────────────────────────────────
#
# Bascule le catalogue PUBLIC (liste + fiche, cf. annonces/api_views.py)
# entre les données de démo internes (seed_demo/seed_parcelles, Annonce.
# source='interne') et les données scrapées Avito/Mubawab importées via
# `manage.py import_scraped_data` (Annonce.source='avito'/'mubawab').
#
# Filtre en lecture seule (cf. annonces/managers.py::dataset_actif()) —
# change cette variable ne supprime ni ne modifie aucune donnée, les deux
# jeux coexistent toujours en base. 'simulated' par défaut : un déploiement
# de prod qui ne définit jamais cette variable ne sert donc jamais de
# données scrapées de test, même si elles ont été importées par erreur.
AKAL_DATASET = env('AKAL_DATASET', default='simulated')


# ──────────────────────────────────────────────
# EMAIL — notifications transactionnelles (réinitialisation de mot de passe)
# ──────────────────────────────────────────────

# Même logique que SENTRY_DSN plus bas : EMAIL_HOST vide = pas de SMTP
# configuré, on bascule sur le backend console (écrit l'email dans les logs)
# plutôt que de lever une erreur ou d'échouer silencieusement en prod.
EMAIL_HOST = env('EMAIL_HOST', default='')
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = env.int('EMAIL_PORT', default=587)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='AKAL <no-reply@akal.ma>')


# ──────────────────────────────────────────────
# CACHE — Redis via django-redis
# ──────────────────────────────────────────────

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Résilience Redis (hardening 2026-08-31) : si Redis est
            # injoignable, cache.get() renvoie None et cache.set() est un
            # no-op, AU LIEU de lever ConnectionInterrupted. Sans ça, une
            # panne Redis fait tomber TOUTE l'API en 500 dès la couche de
            # throttling DRF (check_throttles s'exécute avant la vue, cf.
            # rest_framework/throttling.py) — le cache, une simple
            # optimisation, deviendrait une dépendance dure.
            #
            # Conséquence assumée : pendant une panne Redis, le throttling
            # échoue "ouvert" (les compteurs ne sont plus lus → requêtes
            # laissées passer). C'est le compromis standard : Redis éteint
            # est déjà un incident qui alerte, mieux vaut servir du trafic
            # non throttlé quelques minutes que renvoyer 500 partout. Le
            # cache des limites GIS (geo/api_views.py) retombe lui sur PostGIS.
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'akal',
        'TIMEOUT': 60,  # TTL par défaut : 60 secondes
    }
}

# L'incident Redis reste visible : django-redis logue chaque exception
# ignorée sur le logger 'django_redis.cache' (WARNING) — donc dans la
# console (settings.LOGGING) et, si SENTRY_DSN est défini, dans Sentry
# (LoggingIntegration capture WARNING+ ? non, ERROR+ — mais le repli GIS
# logue lui en WARNING aussi, cf. geo/api_views.py). Sans cette ligne les
# exceptions seraient ignorées SILENCIEUSEMENT.
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True


# ──────────────────────────────────────────────
# LOGGING (audit du 2026-08-03)
# ──────────────────────────────────────────────
#
# Un seul handler (stdout) : Render capture et indexe le stdout/stderr de
# chaque service sans configuration supplémentaire — suffisant comme
# stratégie minimale. Migrer vers un handler dédié (fichier, syslog, service
# de log externe) seulement si Render devient insuffisant.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'akal': {
            'format': '{asctime} {levelname} {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'akal',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # django.request logue déjà les 500 en ERROR et les 400 en WARNING
        # par défaut, via un AdminEmailHandler natif — on le remplace par la
        # console : ADMINS/EMAIL_* ne sont configurés nulle part dans ce
        # projet, donc le comportement par défaut de Django serait un
        # mail_admins silencieusement no-op plutôt qu'une vraie sortie.
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# Sentry (section MONITORING ci-dessous) s'attache à ce logging via
# LoggingIntegration : tout logger.error()/logger.exception() applicatif,
# dans n'importe quelle app (accounts, annonces, geo, messaging), devient un
# événement Sentry sans câblage supplémentaire — pas besoin de déclarer un
# logger dédié par app tant qu'aucune n'appelle encore
# logging.getLogger(__name__) explicitement.


# ──────────────────────────────────────────────
# MONITORING — Sentry (audit du 2026-08-03)
# ──────────────────────────────────────────────
#
# No-op tant que SENTRY_DSN n'est pas défini (dev comme prod) — créer un
# projet Sentry (sentry.io ou self-hosted) et renseigner la variable d'env
# active le monitoring sans toucher au code. DjangoIntegration capture les
# exceptions non gérées (dont les 500 des routes legacy retirées cette même
# session) ; LoggingIntegration capture en plus tout logger.error()/
# logger.exception() applicatif au niveau ERROR+.
SENTRY_DSN = env('SENTRY_DSN', default='')

if SENTRY_DSN:
    # pyrefly: ignore [missing-import]
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=env('SENTRY_ENVIRONMENT', default='development'),
        integrations=[
            DjangoIntegration(),
            # event_level='ERROR' : seuls logger.error()/exception() partent
            # vers Sentry (level=None désactive la capture en simples
            # "breadcrumbs" des logs INFO/DEBUG, bruyante et peu utile ici).
            LoggingIntegration(level=None, event_level='ERROR'),
        ],
        traces_sample_rate=env.float('SENTRY_TRACES_SAMPLE_RATE', default=0.1),
        # RGPD (loi 09-08) — même principe que ProprietaireSerializer
        # (UUID uniquement, cf. annonces/serializers.py) : jamais
        # d'email/nom envoyés à un service tiers par défaut.
        send_default_pii=False,
    )
