"""
Django settings for akal project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
# pyrefly: ignore [missing-import]
import environ

env = environ.Env()

# GDAL / GEOS — Chemins spécifiques pour le développement sous Windows.
# Sur Linux/Docker, les paquets apt (gdal-bin, libgdal-dev) sont détectés automatiquement.
if os.name == 'nt':
    GDAL_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\18\bin\libgdal-35.dll'
    GEOS_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\18\bin\libgeos_c.dll'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# .parent x3 car base.py est dans akal/settings/, donc : settings -> akal -> akal_project
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Lecture du fichier .env
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# DEBUG et ALLOWED_HOSTS sont définis dans dev.py et prod.py


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    # Apps tierces
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',
    'django_filters',

    # Apps du projet
    'accounts',
    'geo',
    'annonces',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'akal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'akal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}
DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'

# Custom User model
AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ──────────────────────────────────────────────
# STOCKAGE MÉDIA — MinIO (dev) / S3-compatible (prod) via django-storages
# ──────────────────────────────────────────────
# Contrat §4.7 : bucket public en lecture, URLs absolues stables, jamais le
# domaine de l'API Django. Mêmes settings dev/prod — seule la valeur des
# variables d'env change (endpoint MinIO local vs S3/CDN prod).
#
# MEDIA_URL n'est plus défini : avec STORAGES['default'] sur S3Storage,
# FieldFile.url délègue au storage (qui construit l'URL depuis les AWS_S3_*
# ci-dessous) — MEDIA_URL serait une deuxième source de vérité pouvant
# diverger silencieusement (ex. si AWS_S3_CUSTOM_DOMAIN change un jour).

AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='akal-media')
AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL', default='http://localhost:9000')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_ADDRESSING_STYLE = 'path'    # requis par MinIO (pas de sous-domaine par bucket)
AWS_QUERYSTRING_AUTH = False        # bucket public en lecture, pas d'URL présignée (§4.7)
AWS_DEFAULT_ACL = None              # la policy du bucket gère la lecture publique
AWS_S3_FILE_OVERWRITE = False       # chaque objet est immuable une fois uploadé
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=31536000',  # photos immuables : cache navigateur 1 an
}

# Domaine public devant le bucket en prod (CDN, ex. media.akal.ma) — vide en
# dev, on sert alors directement depuis l'endpoint MinIO local.
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default='')
AWS_S3_URL_PROTOCOL = 'https:'      # n'a d'effet que si AWS_S3_CUSTOM_DOMAIN est défini

# Vérification TLS de l'endpoint S3 — sans effet ici (endpoint MinIO dev en
# http:// simple) ; pertinent seulement si un endpoint auto-signé passe un
# jour en https:// en local.
AWS_S3_VERIFY = env.bool('AWS_S3_VERIFY', default=True)

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',  # whitenoise inchangé
    },
}

# Cache local de téléchargement pour les scripts de seed (Unsplash) — plus
# jamais servi directement (les médias réels vivent sur MinIO/S3 ci-dessus) ;
# gardé uniquement parce que seed_parcelles.py s'en sert comme répertoire de
# travail local avant upload.
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ──────────────────────────────────────────────
# DJANGO REST FRAMEWORK
# ──────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    # Contrat §4.4 : prix_mad/surface_ha sont des nombres JSON, pas des
    # chaînes. DRF sérialise les DecimalField en string par défaut.
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
    },
}


# ──────────────────────────────────────────────
# AUTH — JWT via cookies httpOnly (avenant v1.1, cf. docs/plans)
# ──────────────────────────────────────────────

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_COOKIE_ACCESS': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_REFRESH_PATH': '/api/auth/',
    # Défauts sûrs pour la prod (frontend et backend sur des sites
    # différents, cf. prod.py) ; dev.py les assouplit pour localhost en HTTP.
    'AUTH_COOKIE_SECURE': True,
    'AUTH_COOKIE_SAMESITE': 'None',
}


# ──────────────────────────────────────────────
# DRF-SPECTACULAR — OpenAPI / Swagger
# ──────────────────────────────────────────────

SPECTACULAR_SETTINGS = {
    'TITLE': 'AKAL API',
    'DESCRIPTION': 'API de la plateforme AKAL — vente de terrains agricoles au Maroc',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# ──────────────────────────────────────────────
# CORS — django-cors-headers
# ──────────────────────────────────────────────

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]

# Requis pour que les cookies JWT (httpOnly) passent sur les requêtes
# cross-origin du frontend (fetch avec credentials: "include").
CORS_ALLOW_CREDENTIALS = True


# ──────────────────────────────────────────────
# CACHE — Redis via django-redis
# ──────────────────────────────────────────────

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'akal',
        'TIMEOUT': 60,  # TTL par défaut : 60 secondes
    }
}


# ──────────────────────────────────────────────
# LOGGING (audit du 2026-08-03)
# ──────────────────────────────────────────────
#
# Un seul handler (stdout) : Render capture et indexe le stdout/stderr de
# chaque service sans configuration supplémentaire — suffisant comme
# stratégie minimale. Migrer vers un handler dédié (fichier, syslog, service
# de log externe) seulement si Render devient insuffisant.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'akal': {
            'format': '{asctime} {levelname} {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'akal',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # django.request logue déjà les 500 en ERROR et les 400 en WARNING
        # par défaut, via un AdminEmailHandler natif — on le remplace par la
        # console : ADMINS/EMAIL_* ne sont configurés nulle part dans ce
        # projet, donc le comportement par défaut de Django serait un
        # mail_admins silencieusement no-op plutôt qu'une vraie sortie.
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# Sentry (section MONITORING ci-dessous) s'attache à ce logging via
# LoggingIntegration : tout logger.error()/logger.exception() applicatif,
# dans n'importe quelle app (accounts, annonces, geo, messaging), devient un
# événement Sentry sans câblage supplémentaire — pas besoin de déclarer un
# logger dédié par app tant qu'aucune n'appelle encore
# logging.getLogger(__name__) explicitement.


# ──────────────────────────────────────────────
# MONITORING — Sentry (audit du 2026-08-03)
# ──────────────────────────────────────────────
#
# No-op tant que SENTRY_DSN n'est pas défini (dev comme prod) — créer un
# projet Sentry (sentry.io ou self-hosted) et renseigner la variable d'env
# active le monitoring sans toucher au code. DjangoIntegration capture les
# exceptions non gérées (dont les 500 des routes legacy retirées cette même
# session) ; LoggingIntegration capture en plus tout logger.error()/
# logger.exception() applicatif au niveau ERROR+.
SENTRY_DSN = env('SENTRY_DSN', default='')

if SENTRY_DSN:
    # pyrefly: ignore [missing-import]
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=env('SENTRY_ENVIRONMENT', default='development'),
        integrations=[
            DjangoIntegration(),
            # event_level='ERROR' : seuls logger.error()/exception() partent
            # vers Sentry (level=None désactive la capture en simples
            # "breadcrumbs" des logs INFO/DEBUG, bruyante et peu utile ici).
            LoggingIntegration(level=None, event_level='ERROR'),
        ],
        traces_sample_rate=env.float('SENTRY_TRACES_SAMPLE_RATE', default=0.1),
        # RGPD (loi 09-08) — même principe que ProprietaireSerializer
        # (UUID uniquement, cf. annonces/serializers.py) : jamais
        # d'email/nom envoyés à un service tiers par défaut.
        send_default_pii=False,
    )
