# Generated by Django 6.0.6 on 2026-07-28 12:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0004_agriscore_created_at"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcelle",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelles",
                to="geo.commune",
            ),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
