# Generated by Django 6.0.6 on 2026-07-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0005_parcelle_localisation_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annonce",
            options={
                "ordering": ["-date_publication", "id"],
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
            },
        ),
    ]
