# Generated by Django 6.0.6 on 2026-08-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0006_alter_annonce_options"),
        ("geo", "0002_provincegeom_communegeom_regionofficielle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcelle",
            name="commune_geom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parcelles",
                to="geo.communegeom",
            ),
        ),
    ]
