# Generated by Django 6.0.6 on 2026-08-11 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0007_parcelle_commune_geom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="source",
            field=models.CharField(
                choices=[
                    ("interne", "Interne"),
                    ("avito", "Avito"),
                    ("mubawab", "Mubawab"),
                ],
                default="interne",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="source_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="annonce",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="acces_eau",
            field=models.CharField(
                blank=True,
                choices=[
                    ("irriguee", "Irriguée"),
                    ("bour", "Bour"),
                    ("mixte", "Mixte"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="acces_routier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("goudron", "Goudron"),
                    ("piste", "Piste"),
                    ("difficile", "Difficile"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="statut_foncier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("melkia", "Melkia"),
                    ("soulaliya", "Soulaliya"),
                    ("guich", "Guich"),
                    ("habous", "Habous"),
                    ("immatricule", "Immatriculé"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="topographie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plat", "Plat"),
                    ("pentu", "Pentu"),
                    ("vallonne", "Vallonné"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="annonce",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id__isnull", False)),
                fields=("source", "source_id"),
                name="annonce_unique_source_id",
            ),
        ),
    ]
