# Generated by Django 6.0.6 on 2026-08-19 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0009_groupe_moderateurs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RechercheSauvegardee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(blank=True, default="", max_length=120)),
                ("criteres", models.JSONField(blank=True, default=dict)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recherches_sauvegardees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recherche sauvegardée",
                "verbose_name_plural": "Recherches sauvegardées",
                "db_table": "recherche_sauvegardee",
                "ordering": ["-created_at"],
            },
        ),
    ]
