# Generated by Django 6.0.6 on 2026-08-20 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0010_recherchesauvegardee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="annonce",
            index=models.Index(
                fields=["statut", "source", "-date_publication"],
                name="annonce_statut_source_pub_idx",
            ),
        ),
    ]
