# Generated by Django 6.0.6 on 2026-09-07 11:49

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0011_annonce_statut_source_pub_index"),
        ("geo", "0003_alter_communegeom_type_commune"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="annonce",
            name="prix_mad",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix en MAD",
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"),
                        message="Le prix doit être strictement positif.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="parcelle",
            name="surface_ha",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Surface en hectares",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"),
                        message="La superficie doit être strictement positive.",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="annonce",
            constraint=models.CheckConstraint(
                condition=models.Q(("prix_mad__gt", 0)), name="annonce_prix_mad_positif"
            ),
        ),
        migrations.AddConstraint(
            model_name="parcelle",
            constraint=models.CheckConstraint(
                condition=models.Q(("surface_ha__gt", 0)),
                name="parcelle_surface_ha_positive",
            ),
        ),
    ]
