# Generated by Django 6.0.8 on 2026-09-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0012_garde_fous_prix_surface_positifs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgriScore",
        ),
    ]
