# Generated by Django 6.0.8 on 2026-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0013_delete_agriscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="motif_moderation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
