# Generated by Django 6.0.8 on 2026-09-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0014_annonce_motif_moderation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annonce",
            options={
                "ordering": ["-date_publication", "id"],
                "permissions": [
                    ("valider_annonce", "Peut valider ou refuser une annonce"),
                    ("suspendre_annonce", "Peut suspendre une annonce"),
                ],
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
            },
        ),
    ]
