# Generated by Django 6.0.6 on 2026-08-10 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0007_parcelle_commune_geom"),
        ("messaging", "0002_remove_destinataire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_notif",
                    models.CharField(
                        choices=[
                            ("nouveau_message", "Nouveau message"),
                            ("nouveau_favori", "Nouveau favori"),
                            ("contact_recu", "Contact reçu"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("is_lu", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annonce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="annonces.annonce",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
