# Generated by Django 6.0.6 on 2026-08-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notif",
            field=models.CharField(
                choices=[
                    ("nouveau_message", "Nouveau message"),
                    ("nouveau_favori", "Nouveau favori"),
                    ("contact_recu", "Contact reçu"),
                    ("alerte_recherche", "Alerte recherche sauvegardée"),
                ],
                max_length=30,
            ),
        ),
    ]
