# Generated by Django 6.0.6 on 2026-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigurationAgriScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Coché : le passeport interroge les vraies sources (Copernicus, Open-Meteo, SoilGrids, OSRM). Décoché : passeport simulé, aucune API externe appelée.",
                        verbose_name="pipeline actif (API réelles)",
                    ),
                ),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "configuration AgriScore",
                "verbose_name_plural": "configuration AgriScore",
                "db_table": "agriscore_configuration",
            },
        ),
    ]
