# Generated by Django 6.0.8 on 2026-09-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationagriscore',
            name='poids_acces',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='poids accès (%)'),
        ),
        migrations.AddField(
            model_name='configurationagriscore',
            name='poids_climat',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='poids climat (%)'),
        ),
        migrations.AddField(
            model_name='configurationagriscore',
            name='poids_ndvi',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='poids NDVI (%)'),
        ),
        migrations.AddField(
            model_name='configurationagriscore',
            name='poids_sol',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='poids sol (%)'),
        ),
        migrations.AddField(
            model_name='configurationagriscore',
            name='poids_topo',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='poids topographie (%)'),
        ),
    ]
