# Generated by Django 6.0.8 on 2026-09-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriscore', '0002_ponderations_configurables'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquePasseport',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('compteur', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'statistique passeport (consultations)',
                'verbose_name_plural': 'statistiques passeport (consultations)',
                'db_table': 'agriscore_statistique_passeport',
            },
        ),
    ]
