# Generated by Django 6.0.6 on 2026-08-06 10:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvinceGeom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=150)),
                ("nom_ar", models.CharField(blank=True, max_length=150)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "Province (géométrie officielle)",
                "verbose_name_plural": "Provinces (géométrie officielle)",
                "db_table": "province_geom",
            },
        ),
        migrations.CreateModel(
            name="CommuneGeom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_fid", models.PositiveIntegerField(unique=True)),
                ("libelle", models.CharField(max_length=100)),
                ("nom_affichage", models.CharField(db_index=True, max_length=100)),
                (
                    "type_commune",
                    models.CharField(
                        choices=[("CR", "Rurale"), ("MU", "Urbaine")], max_length=2
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communes",
                        to="geo.provincegeom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commune (géométrie officielle)",
                "verbose_name_plural": "Communes (géométrie officielle)",
                "db_table": "commune_geom",
            },
        ),
        migrations.CreateModel(
            name="RegionOfficielle",
            fields=[
                (
                    "code",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("slug", models.SlugField(unique=True)),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Région officielle",
                "verbose_name_plural": "Régions officielles",
                "db_table": "region_officielle",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__gte", 1), ("code__lte", 12)),
                        name="region_officielle_code_1_12",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="provincegeom",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provinces",
                to="geo.regionofficielle",
            ),
        ),
    ]
