# Generated by Django 6.0.6 on 2026-08-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_provincegeom_communegeom_regionofficielle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communegeom",
            name="type_commune",
            field=models.CharField(
                blank=True,
                choices=[("CR", "Rurale"), ("MU", "Urbaine")],
                max_length=2,
                null=True,
            ),
        ),
    ]
